var madr_gui = ''; 

toolbar_gui = '';
toolbar_gui += '<div id="madr_toolbar_open_button_wrapper">';
toolbar_gui += '    <div id="madr_toolbar_open_button">';
toolbar_gui += '    ';
toolbar_gui += '    </div>';
toolbar_gui += '</div>';
toolbar_gui += '';
toolbar_gui += '<div id="madr_toolbar_wrapper" style="display: none;">';
toolbar_gui += '    <div id="madr_toolbar_toolbar">';
toolbar_gui += '        <div class="madr_toolbar_button dlg_open_btn" data-dlg-name="mdr_martcalc_dlg" title="Martingale Calculator"><i class="fa fa-calculator"></i></div>';
toolbar_gui += '        <div class="madr_toolbar_button dlg_open_btn" data-dlg-name="mdr_systemvars_dlg" title="System Variables"><i class="fa fa-gears"></i></div>';
toolbar_gui += '        <div class="madr_toolbar_button dlg_open_editor" title="Bot Code Editor"><i class="fa fa-code"></i></div>';
toolbar_gui += '        <div class="madr_toolbar_button dlg_open_btn" data-dlg-name="mdr_heights_dlg" title="Win/Loss Heights"><i class="fa fa-bar-chart"></i></div>';
toolbar_gui += '        <div class="madr_toolbar_button dlg_open_btn" data-dlg-name="mdr_minresults_dlg" title="Roll Results"><i class="fa fa-university"></i></div>';
toolbar_gui += '        <div class="madr_toolbar_button dlg_open_btn" data-dlg-name="mdr_lastheights_dlg" title="Last Heights"><i class="fa fa-bars"></i></div>';
toolbar_gui += '        <div class="madr_toolbar_button dlg_open_btn" data-dlg-name="mdr_about_dlg" title="About"><i class="fa fa-info-circle"></i></div>';
toolbar_gui += '        <div class="clearfix"></div>';
toolbar_gui += '    </div>';
toolbar_gui += '    <div id="madr_toolbar_close_button"></div>';
toolbar_gui += '</div>';

madr_gui += toolbar_gui; 

heights_gui = '';
heights_gui += '<div class="mdr_dialog" id="mdr_heights_dlg" title="Win/Loss Runs" style="display: none;">';
heights_gui += '    <div id="heights_display_wrapper">';
heights_gui += '    <div id="heights_reset_btn" class="btn_black">Reset</div>';
heights_gui += '        <div id="heights_display_section_win">';
heights_gui += '            <div class="heights_display_section">';
heights_gui += '                <table class="mdr_display_table" id="win_heights_table" style="width: 100%;">';
heights_gui += '                    <thead>';
heights_gui += '                        <th colspan="2"><div style="text-align:center;">Wins</div></th>';
heights_gui += '                    </thead>';
heights_gui += '                    <tbody></tbody> ';
heights_gui += '                </table>';
heights_gui += '            </div>';
heights_gui += '        </div>';
heights_gui += '        <div id="heights_display_section_loss">';
heights_gui += '            <div class="heights_display_section">';
heights_gui += '                <table class="mdr_display_table" id="loss_heights_table" style="width: 100%;">';
heights_gui += '                    <thead>';
heights_gui += '                        <th colspan="2">Losses</th>';
heights_gui += '                    </thead>';
heights_gui += '                    <tbody><tbody></tbody></tbody> ';
heights_gui += '                </table>';
heights_gui += '            </div>';
heights_gui += '        </div>        ';
heights_gui += '    </div>';
heights_gui += '</div>    ';

madr_gui += heights_gui;

editors_gui = '';
editors_gui += '<div class="mdr_dialog" id="mdr_editor_main_dlg" title="Main Bot Code" style="display: none;">';
editors_gui += '    <div class="editor_wrapper">';
editors_gui += '        <div id="mdr_main_bot_editor_toolbar">';
//editors_gui += '            <div id="" class="mdr_button smallerbtn btn_black" title="New Code"><i class="fa fa-file"></i></div>';
//editors_gui += '            <div id="" class="mdr_button smallerbtn btn_black" title="Save Code"><i class="fa fa-save"></i></div>';
//editors_gui += '            <div id="" class="mdr_button smallerbtn btn_black" title="Load Code"><i class="fa fa-folder"></i></div>';
editors_gui += '        </div>';
editors_gui += '        <div id="mdr_main_bot_editor" class="mdr_editor"></div>';
editors_gui += '        <div id="mdr_main_bot_editor_controls">';
editors_gui += '            <div id="mdr_execute_code_btn" class="mdr_button smallerbtn btn_green">Execute</div>';
editors_gui += '            <div id="mdr_terminate_code_btn" class="mdr_button smallerbtn btn_disabled">Terminate</div>';
editors_gui += '            <div id="mdr_terminate_onw_code_btn" class="mdr_button smallerbtn btn_red">Terminate Next Win</div>';
editors_gui += '        </div>';
editors_gui += '    </div>';
editors_gui += '</div>';
editors_gui += '<div id="mdr_editor_start_dlg" title="Startup Bot Code" style="display: none;">';
editors_gui += '    <div class="editor_wrapper">';
editors_gui += '        <div id="mdr_start_bot_editor" class="mdr_editor"></div>';
editors_gui += '    </div>';
editors_gui += '</div>';

madr_gui += editors_gui;

calculator_gui = '';
calculator_gui += '<div class="mdr_dialog" id="mdr_martcalc_dlg" title="Martingale Calculator" style="display: none;">';
calculator_gui += '<div class="dialog_light_section">';
calculator_gui += '    <table style="width: 100%;">';
calculator_gui += '        <tr>';
calculator_gui += '            <td width="70">Start Bet</td>';
calculator_gui += '            <td><input id="mart_calc_bet_amount" class="mdr_input" value="1.00000000" style="width: 100%;" /></td>';
calculator_gui += '        </tr>';
calculator_gui += '        <tr>';
calculator_gui += '            <td>Multipier</td>';
calculator_gui += '            <td><input id="mart_calc_bet_multi" class="mdr_input" value="2"  style="width: 100%;"/></td>';
calculator_gui += '        </tr>';
calculator_gui += '        <tr>';
calculator_gui += '            <td># of Rolls</td>';
calculator_gui += '            <td><input id="mart_calc_rolls" class="mdr_input" value="15"  style="width: 100%;"/></td>';
calculator_gui += '        </tr>';
calculator_gui += '        <tr>';
calculator_gui += '            <td># Precision</td>';
calculator_gui += '            <td><input id="mart_calc_pre" class="mdr_input" value="8"  style="width: 100%;"/></td>';
calculator_gui += '        </tr>';
calculator_gui += '        <tr>';
calculator_gui += '            <td colspan="2" style="text-align: center;"><div id="do_calc_mart_btn" class="mdr_button btn_green smallerbtn" style="width: 150px;">Calculate</div></a></td>';
calculator_gui += '        </tr>';
calculator_gui += '    </table>';
calculator_gui += '    <div style="width: 100%;height: 2px;"></div>';
calculator_gui += '</div>';
calculator_gui += '<div class="display_scroller_wrapper">';
calculator_gui += '<div class="display_scroller">';
calculator_gui += '<table class="mdr_display_table" id="margingale_calc_display_table" style="width: 100%;" cellpadding="0" cellspacing="0">';
calculator_gui += '    <thead>';
calculator_gui += '        <th>Loss #</th>    ';
calculator_gui += '        <th>Bet Amount</th>';
calculator_gui += '        <th>Amount To Here</th>';
calculator_gui += '    </thead>';
calculator_gui += '    <tbody></tbody>';
calculator_gui += '</table>';
calculator_gui += '</div>';
calculator_gui += '</div>';
calculator_gui += '';
calculator_gui += '</div>';

madr_gui += calculator_gui;

systemvars_gui = '';
systemvars_gui += '<div class="mdr_dialog" id="mdr_systemvars_dlg" title="System Variables" style="display: none;">';
systemvars_gui += '    <table>';
systemvars_gui += '        <tr>';
systemvars_gui += '            <td class="editor_link">botCurrBalance</td>';
systemvars_gui += '            <td><span class="botCurrBalance">0</span></td>';
systemvars_gui += '            <td class="editor_link">botStartTime</td>';
systemvars_gui += '            <td><span class="botStartTime" width="125">0</span></td>';
systemvars_gui += '            <td class="editor_link">botTotalSeconds</td>';
systemvars_gui += '            <td><span class="botTotalSeconds">0</span></td>';
systemvars_gui += '            <td class="">Run Time</td>';
systemvars_gui += '            <td><span class="runTime">00:00:00</span></td>';
systemvars_gui += '            ';
systemvars_gui += '        </tr>';
systemvars_gui += '        <tr>';
systemvars_gui += '            <td class="editor_link">botBaseBet</td>';
systemvars_gui += '            <td><span class="botBaseBet">0</span></td>';
systemvars_gui += '            <td class="editor_link">botBaseGame</td>';
systemvars_gui += '            <td><span class="botBaseGame">0</span></td>';
systemvars_gui += '            <td class="editor_link">botBaseType</td>';
systemvars_gui += '            <td><span class="botBaseType">0</span></td>';
systemvars_gui += '            <td class="editor_link">botBaseMulti</td>';
systemvars_gui += '            <td><span class="botBaseMulti">0</span></td>';
systemvars_gui += '        </tr>';
systemvars_gui += '        <tr>';
systemvars_gui += '            <td class="editor_link">botCurrBet</td>';
systemvars_gui += '            <td><span class="botCurrBet">0</span></td>';
systemvars_gui += '            <td class="editor_link">botCurrGame</td>';
systemvars_gui += '            <td><span class="botCurrGame">0</span></td>';
systemvars_gui += '            <td class="editor_link">botCurrType</td>';
systemvars_gui += '            <td><span class="botCurrType">0</span></td>';
systemvars_gui += '            <td class="editor_link">botCurrMulti</td>';
systemvars_gui += '            <td><span class="botCurrMulti">0</span></td>';
systemvars_gui += '        </tr>    ';
systemvars_gui += '        <tr>';
systemvars_gui += '            <td class="editor_link">botCurrWinRun</td>';
systemvars_gui += '            <td><span class="botCurrWinRun">0</span></td>';
systemvars_gui += '            <td class="editor_link">botHiWinRun</td>';
systemvars_gui += '            <td><span class="botHiWinRun">0</span></td>';
systemvars_gui += '            <td class="editor_link">botCurrLossRun</td>';
systemvars_gui += '            <td><span class="botCurrLossRun red">0</span></td>';
systemvars_gui += '            <td class="editor_link">botHiLossRun</td>';
systemvars_gui += '            <td><span class="botHiLossRun red">0</span></td>';
systemvars_gui += '        </tr>             ';
systemvars_gui += '        <tr>';
systemvars_gui += '            <td class="editor_link">botTotalBets</td>';
systemvars_gui += '            <td><span class="botTotalBets">0</span></td>';
systemvars_gui += '            <td class="editor_link">botTotalWagered</td>';
systemvars_gui += '            <td><span class="botTotalWagered">0</span></td>';
systemvars_gui += '            <td class="editor_link">botTotalProfit</td>';
systemvars_gui += '            <td><span class="botTotalProfit">0</span></td>';
systemvars_gui += '            <td class="editor_link">botTotalRuns</td>';
systemvars_gui += '            <td><span class="botTotalRuns">0</span></td>';
systemvars_gui += '        </tr>             ';
systemvars_gui += '        <tr>';
systemvars_gui += '            <td id="user_var_label_1" class="user_var_label">User 1</td>';
systemvars_gui += '            <td id="user_var_value_1" class="user_var_value">0</td>';
systemvars_gui += '            <td id="user_var_label_2" class="user_var_label">User 2</td>';
systemvars_gui += '            <td id="user_var_value_2" class="user_var_value">0</td>';
systemvars_gui += '            <td id="user_var_label_3" class="user_var_label">User 3</td>';
systemvars_gui += '            <td id="user_var_value_3" class="user_var_value">0</td>';
systemvars_gui += '            <td id="user_var_label_4" class="user_var_label">User 4</td>';
systemvars_gui += '            <td id="user_var_value_4" class="user_var_value">0</td>';
systemvars_gui += '        </tr>        ';
systemvars_gui += '        <tr>';
systemvars_gui += '            <td id="user_var_label_5" class="user_var_label">User 5</td>';
systemvars_gui += '            <td id="user_var_value_5" class="user_var_value">0</td>';
systemvars_gui += '            <td id="user_var_label_6" class="user_var_label">User 6</td>';
systemvars_gui += '            <td id="user_var_value_6" class="user_var_value">0</td>';
systemvars_gui += '            <td id="user_var_label_7" class="user_var_label">User 7</td>';
systemvars_gui += '            <td id="user_var_value_7" class="user_var_value">0</td>';
systemvars_gui += '            <td id="user_var_label_8" class="user_var_label">User 8</td>';
systemvars_gui += '            <td id="user_var_value_8" class="user_var_value">0</td>';
systemvars_gui += '        </tr>        ';
systemvars_gui += '    </table>';
systemvars_gui += '</div>';
systemvars_gui += '';
madr_gui += systemvars_gui;

results_gui = '';
results_gui += '<div id="mdr_minresults_dlg" title="Roll Results" style="display: none;">';
results_gui += '    <div class="results_display_section">';
results_gui += '    <table style="width: 100%;">';
results_gui += '        <thead>';
results_gui += '            <th><div style="text-align: left;width:75px!important;">ID</div></th>';
results_gui += '            <th><div style="text-align: center;">Time</div></th>';
results_gui += '            <th><div style="text-align: center;">Bet</div></th>';
results_gui += '            <th><div style="text-align: center;">Roll</div></th>';
results_gui += '            <th><div style="text-align: center;">Target</div></th>';
results_gui += '            <th><div style="text-align: right;">Profit</div></th>';
results_gui += '        </thead>';
results_gui += '        <tbody id="results_display_body"></tbody>';
results_gui += '    </table>';
results_gui += '    </div>';
results_gui += '</div>';

madr_gui += results_gui;

lastheight_gui = '';
lastheight_gui += '<div id="mdr_lastheights_dlg" title="Last Heights" style="display: none;">';
lastheight_gui += '    <table style="width: 100%;" id="last_heights_table">';
lastheight_gui += '        <tr>';
lastheight_gui += '            <td>Win</td>';
lastheight_gui += '            <td id="last_w_1">0</td>';
lastheight_gui += '            <td id="last_w_2">0</td>';
lastheight_gui += '            <td id="last_w_3">0</td>';
lastheight_gui += '            <td id="last_w_4">0</td>';
lastheight_gui += '            <td id="last_w_5">0</td>';
lastheight_gui += '            <td id="last_w_6">0</td>';
lastheight_gui += '            <td id="last_w_7">0</td>';
lastheight_gui += '            <td id="last_w_8">0</td>';
lastheight_gui += '            <td id="last_w_9">0</td>';
lastheight_gui += '            <td id="last_w_10">0</td>';
lastheight_gui += '            <td id="last_w_11">0</td>';
lastheight_gui += '            <td id="last_w_12">0</td>';
lastheight_gui += '            <td id="last_w_13">0</td>';
lastheight_gui += '            <td id="last_w_14">0</td>';
lastheight_gui += '            <td id="last_w_15">0</td>';
lastheight_gui += '            <td id="last_w_16">0</td>';
lastheight_gui += '            <td id="last_w_17">0</td>';
lastheight_gui += '            <td id="last_w_18">0</td>';
lastheight_gui += '            <td id="last_w_19">0</td>';
lastheight_gui += '            <td id="last_w_20">0</td>';
lastheight_gui += '        </tr>';
lastheight_gui += '        <tr>';
lastheight_gui += '            <td>Loss</td>';
lastheight_gui += '            <td id="last_l_1">0</td>';
lastheight_gui += '            <td id="last_l_2">0</td>';
lastheight_gui += '            <td id="last_l_3">0</td>';
lastheight_gui += '            <td id="last_l_4">0</td>';
lastheight_gui += '            <td id="last_l_5">0</td>';
lastheight_gui += '            <td id="last_l_6">0</td>';
lastheight_gui += '            <td id="last_l_7">0</td>';
lastheight_gui += '            <td id="last_l_8">0</td>';
lastheight_gui += '            <td id="last_l_9">0</td>';
lastheight_gui += '            <td id="last_l_10">0</td>';
lastheight_gui += '            <td id="last_l_11">0</td>';
lastheight_gui += '            <td id="last_l_12">0</td>';
lastheight_gui += '            <td id="last_l_13">0</td>';
lastheight_gui += '            <td id="last_l_14">0</td>';
lastheight_gui += '            <td id="last_l_15">0</td>';
lastheight_gui += '            <td id="last_l_16">0</td>';
lastheight_gui += '            <td id="last_l_17">0</td>';
lastheight_gui += '            <td id="last_l_18">0</td>';
lastheight_gui += '            <td id="last_l_19">0</td>';
lastheight_gui += '            <td id="last_l_20">0</td>';
lastheight_gui += '        </tr>';
lastheight_gui += '    </table>';
lastheight_gui += '</div>';

madr_gui += lastheight_gui;

about_gui = '';
about_gui += '<div id="mdr_about_dlg" title="About" style="display: none;">';
about_gui += '<div id="mdr_about_wrapper">';
about_gui += '<div id="mdr_about_logo"></div>';
about_gui += '<div id="mdr_about_title">MadRoller\'s Dice System</div>';
about_gui += '<div id="mdr_about_version">Version : 0.1.8</div>';
about_gui += '<div id="mdr_about_donation_title">Always Free! Donations Welcome!</div>';
about_gui += '<div id="mdr_about_donation_addresses">';
about_gui += '<span>BTC:</span> 15F1t1d3ePWEsV8qoAV58NKnj6Fydf9RVi<br>';
about_gui += '<span>LTC:</span> LNbJqqaEkNMQuoTgQ9tvFpDqMwvTtCaucP<br>';
about_gui += '<span>DOGE:</span> D7McjTxCq1yutWPCxzuntiqxSQxy44wtKA<br>';
about_gui += '<span>RDD:</span> RiheMMWVGfYtR4Qa7N6CpXAJneqiHPQkiG<br>';
about_gui += '<span>CLAM:</span> x9u8cjcuSAMJ2eBK7pneEHtqBbeFPeS5Gu<br>';
about_gui += '</div>';
about_gui += '<div id="mdr_about_website"><span>Website:</span> http://themadroller.com</div>';
about_gui += '</div>';
about_gui += '</div>';

madr_gui += about_gui;

console.log('Injecting UI');

$('body').append(madr_gui);

